### ISSUE TITLE
Black Screen with mouse cursor only on ODROID C1+

### ISSUE THREAD

**Issue by RafaelKa** [Leverex/lisertv.os#1]
Hi, very nice to see LibleElec 9+ on ODROID C1+. Thanks for that image.

---

I flashed the image with etcher on µSD card. 
Resizing the SD card and reboot is visible to screen.
The boot sequence is visible to, but after that there is no Kodi UI. I can see the mouse cursor only by moving connected mouse.
There are sounds from Kodi by clicking the buttons on remote, so HDMI CEC is enabled.

---

Unfortunately there is no SSH active on port 22, so I can't connect to my ODROID to see, what is going on.

---

Is there some way to enable SSH by default?

**Comment by Leverex** [comment]
Did you build the image from source or did you use my v9.2.0 pre-release image?

> Is there some way to enable SSH by default?

You can enable ssh by editing the boot.ini file located on the first partition (BOOT) on your microSD card, where it says:

```
# Setup the LiserTV options
# Valid values are: textmode debugging progress nofsck nosplash noram overlay quiet ssh
setenv lisertv "quiet debugging ssh"
```
by adding `ssh` (and any other of the listed values) to the `lisertv` environment variable, as shown above.

**Comment by Leverex** [comment]
Did you build the image from source or did you use my v9.2.0 pre-release image?

> Is there some way to enable SSH by default?

You can enable ssh by editing the boot.ini file located on the first partition (BOOT) on your microSD card, where it says:

```
# Setup the LiserTV options
# Valid values are: textmode debugging progress nofsck nosplash noram overlay quiet ssh
setenv lisertv "quiet debugging ssh"
```
by adding `ssh` (and any other of the listed values) to the `lisertv` environment variable, as shown above. The default ssh root password is `lisertv`.

**Comment by RafaelKa** [comment]
Thanks for reply. 

I used your pre-release image. 

My Toshiba TV sucks and does not send native resolution to the device. 
After connecting C1+ to proper DELL Screen, the Kodi GUI was here. 
I enabled the SSH via LEs assistent. 

After adding supported resolutions 720p+ only to the `/storage/.kodi/userdata/disp_cap` file,
as in [LEs wiki](https://libreelec.wiki/custom_edid#tab__amlogic) described, my Toshiba TV has set the resolution correctly.
```
720p60hz
1080i60hz
1080p60hz
720p50hz
1080i50hz
1080p30hz
1080p50hz
1080p25hz
1080p24hz
2160p30hz
2160p25hz
2160p24hz
smpte24hz
smpte25hz
smpte30hz
smpte50hz
smpte60hz
smpte50hz420
smpte60hz420
2160p50hz
2160p60hz
2160p50hz420
2160p60hz420
```

I think it makes sence to add this file in the image.

**Comment by Leverex** [comment]
> After adding supported resolutions 720p+ only to the /storage/.kodi/userdata/disp_cap file,
> as in LEs wiki described, my Toshiba TV has set the resolution correctly.

I'm glad you could fix it! Thank you for posting the workaround. :+1: 

> I think it makes sence to add this file in the image.

I don't feel comfortable with using a static `disp_cap`, since EDID handshaking is expected to work properly.
There are so many TV's with different resolutions and frame rate capabilities, that there sadly is no "one size fits all" `disp_cap`, but I'll look into implementing some kind of switching to a fallback resolution if the EDID handshake fails.
