### ISSUE TITLE
Cannot mount ext4 partition

### ISSUE THREAD

**Issue by p3k** [Leverex/lisertv.os#2]
I am trying to access the contents of an HD I used with elementary OS and cannot work out how to mount it:

```plain
# blkid 
/dev/loop0: TYPE="squashfs"
/dev/mmcblk0p1: SEC_TYPE="msdos" LABEL_FATBOOT="BOOT" LABEL="BOOT" UUID="0707-0044" TYPE="vfat" PARTUUID="43e2de21-01"
/dev/mmcblk0p2: LABEL="STORAGE" UUID="fc2d3e39-6df0-4f47-9e03-9ace21fd8976" TYPE="ext4" PARTUUID="43e2de21-02"
/dev/sdb1: LABEL="Seagate Backup Plus Drive" UUID="90C6621EC6620536" TYPE="ntfs" PTTYPE="atari" PARTUUID="23638b27-01"
/dev/sda1: LABEL="Linux" UUID="1b40da23-9359-42b2-9210-1ee5211066e6" TYPE="ext4" PARTLABEL="Linux filesystem" PARTUUID="5090b1d9-9a33-4338-8c3a-760898448753"
/dev/mmcblk0: PTUUID="43e2de21" PTTYPE="dos"

# mount /dev/sda1 /tmp/linux
NTFS signature is missing.
Failed to mount '/dev/sda1': Invalid argument
The device '/dev/sda1' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
mount: mounting /dev/sda1 on /tmp/linux/ failed: Invalid argument

# mount -t ext4 /dev/sda1 /tmp/linux
mount: mounting /dev/sda1 on /tmp/linux failed: Invalid argument
```

There seems to be no `mount.ext` or `mount.ext4` binary, and I am not sure how to proceed. Any suggestions?

**Comment by Leverex** [comment]
Unfortunately the old 3.10 kernel that's being shipped with the Odroid C1 image doesn't support some of the default features of mkfs.ext4 on modern systems with a newer kernel. A possible workaround would be to disable the journal feature of the ext4 partition with the following command:
```
tune2fs -O ^has_journal /dev/sdXn
```
or by using another filesystem like ext2 or NTFS.

**Comment by p3k** [comment]
thanks for the reply, @Leverex. i understand the issue is with the older kernel, just was not sure if i made a mistake.

i decided to reformat the disks using ntfs now, this seems to be the simplest and most compatible route for my setup now.
