### ISSUE TITLE
Black screen after LiserTV logo

### ISSUE THREAD

**Issue by Panderine** [Leverex/lisertv.os#4]
Hi!, 

I'm using v9.2.2 on an odroid C1 board. After the initial boot, resize and Lisertv logo, Kodi starts. When it starts I can hear the menu sound, and I can move around using keyboard while having a black screen. My TV shows it's running at 1080x60hz, if I move the mouse I see the white arrow and It seems to be in a small black window smaller than the screen size since the mouse disappear at what seems the edge of that small window. Any idea what could be wrong. I don't have this issue using ubuntu minimal and kodi, as well as on android images. But i tried another Libreelec version for C1 and I have the same issue.

Pastekodi output:
http://ix.io/2ADv

**Comment by Leverex** [comment]
Please have a look at #1.

Kodi depends on a valid EDID information in ```/sys/class/amhdmitx/amhdmitx0/disp_cap``` to detect the supported resolutions and frame rate modes of your TV. If the EDID handshake fails, there is no data in ```disp_cap``` and you get the described behaviour.

You can override the EDID information by creating a text file in ```/storage/.kodi/userdata/disp_cap``` with the modes supported by your TV, each separated by a newline.

Example ```/storage/.kodi/userdata/disp_cap```:
```
480p60hz
576p50hz
720p50hz
720p60hz
1080i50hz
1080i60hz
1080p24hz
1080p25hz
1080p30hz
1080p50hz
1080p60hz
```

After that you have to restart Kodi or reboot your device.

**Comment by Panderine** [comment]
Yes indeed, I don't get  valid EDID information. 
LiserTV:~ # cat /sys/class/amhdmitx/amhdmitx0/disp_cap
null edid

I tried that but as soon as I reboot, I get into a crash loop I believe when Kodi starts (since I can get a ssh connection just before). Will try again and report. Thanks!

EDIT: yep... adding that file make the c1 reboot loop just as kodi starts. Can I add debug to the boot.ini parameters to see something else?

**Comment by Panderine** [comment]
Sorry to spam. If I try the oficial ubuntu minimal image and install kodi-fdev it works :(

**Comment by Leverex** [comment]
One option would be to mount the sdcard on another system and investigate the log files located in your ```STORAGE``` partition. You can find the logs in ```.kodi/userdata/temp/kodi.log``` and ```.kodi/userdata/temp/kodi_crashlog_*.log```.

Another option would be to add ```textmode``` and ```debugging```  to the lisertv environment variable in ```boot.ini```, to get a console after startup:
```
# Setup the LiserTV options
# Valid values are: textmode debugging progress nofsck nosplash noram overlay quiet ssh
setenv lisertv "textmode debugging ssh"
```

Providing the "fake" EDID information in ```/storage/.kodi/userdata/disp_cap``` works for me on an Odroid C1+, I'm not able to reproduce this issue, but your logs may give a clue.

**Comment by Leverex** [comment]
One option would be to mount the sdcard on another system and investigate the log files located in your STORAGE partition. You can find the logs in .kodi/userdata/temp/kodi.log and .kodi/userdata/temp/kodi_crashlog_*.log.

Another option would be to add textmode and debugging to the lisertv environment variable in boot.ini, to get a console after startup:

# Setup the LiserTV options
# Valid values are: textmode debugging progress nofsck nosplash noram overlay quiet ssh
setenv lisertv "textmode debugging ssh"

Providing the "fake" EDID information in /storage/.kodi/userdata/disp_cap works for me on an Odroid C1+, I'm not able to reproduce this issue, but your logs may give a clue about what's happening on your device.

**Comment by Leverex** [comment]
One option would be to mount the sdcard on another system and investigate the log files located in your ```STORAGE``` partition. You can find the logs in ```.kodi/userdata/temp/kodi.log``` and ```.kodi/userdata/temp/kodi_crashlog_*.log```.

Another option would be to add ```textmode``` and ```debugging``` to the lisertv environment variable in ```boot.ini```, to get a console after startup:

```
# Setup the LiserTV options
# Valid values are: textmode debugging progress nofsck nosplash noram overlay quiet ssh
setenv lisertv "textmode debugging ssh"
```

Providing the "fake" EDID information in ```/storage/.kodi/userdata/disp_cap``` works for me on an Odroid C1+, I'm not able to reproduce this issue, but your logs may give a clue about what's happening on your device.

**Comment by Leverex** [comment]
One option would be to mount the sdcard on another system and investigate the log files located on your ```STORAGE``` partition. You can find the logs in ```.kodi/userdata/temp/kodi.log``` and ```.kodi/userdata/temp/kodi_crashlog_*.log```.

Another option would be to add ```textmode``` and ```debugging``` to the lisertv environment variable in ```boot.ini```, to get a console after startup:

```
# Setup the LiserTV options
# Valid values are: textmode debugging progress nofsck nosplash noram overlay quiet ssh
setenv lisertv "textmode debugging ssh"
```

Providing the "fake" EDID information in ```/storage/.kodi/userdata/disp_cap``` works for me on an Odroid C1+, I'm not able to reproduce this issue, but your logs may give a clue about what's happening on your device.

**Comment by Panderine** [comment]
Thanks Leverex, i'll try that. This is an old rev3 C1 (not +) so I know some HW differences exists specially regarding CEC and HDMI so this might be an issue with that. To be honest I was never able to use OpenELEC the time I tried. Always had a different issue. Thanks anyway!

**Comment by moritzhoewer** [comment]
Hi,
I am experiencing similar behaviour (black screen, only mouse cursor). But I don't get any logs from Kodi. Might be because the boot process fails when it tries to mount the `/dev/mmcblk0p2` partition to `/storage` with the unhelpful error message "Invalid argument". I can make it continue, but the it just hangs when starting Kodi. I can boot in textmode though, but `/storage` is not mounted. When I start Kodi, it fails and complains about missing files in `/storage`

The partition mounts fine on my desktop and `fsck` doesn't report any errors. Neither on the Odroid nor on my desktop.

Any ideas why it doesn't mount on the odroid?

(I am also using a C1 (not +))

**Comment by Leverex** [comment]
The issue you are facing is likely unrelated to this issue.

Unfortunately the 3.10 kernel can't handle some of the "new" ext4 journaling features (mounting and unmounting the partition on a modern system is enough to make it unusable with 3.10).

I found out that if I ever mounted the ```STORAGE``` ext4 partition on my desktop system, I always had to clear the journaling feature of the filesystem, to keep it compatible with the older kernel. I do that by issuing the command
```
sudo tune2fs -O ^has_journal /dev/mmcblk0p2
```
right after unmounting the ```STORAGE``` partition (the device name can be different, depending on your card reader).

**Comment by moritzhoewer** [comment]
Thanks, that fixed the issue with the filesystem.
I then actually proceeded to face the issue originally described here, but 

> You can override the EDID information by creating a text file in `/storage/.kodi/userdata/disp_cap` with the modes supported by your TV, each separated by a newline.

fixed the issue for me.

Thanks for the quick reply and help :)

**Comment by Leverex** [comment]
You're welcome!
Also thanks for letting me know that it works for you on the C1. :+1:
