### ISSUE TITLE
Howto build a working image ?

### ISSUE THREAD

**Issue by powo01** [Leverex/lisertv.os#6]
Hello,

I have cloned the repo. The build process is working but the image is not booting into kodi. During the boot see the libreElec boot logo

I have used the following build command

PROJECT=S805 ARCH=arm DEVICE=Odroid_C1 make  image

Many thanks for your help in advance

Regards,
Wolfgang

**Comment by Leverex** [comment]
I'm not sure about the problem, but in order to build LiserTV, you need to specify the correct distribution.
Please try the following command:
```
DISTRO=LiserTV PROJECT=S805 DEVICE=Odroid_C1 ARCH=arm make image
```
Let's see if that helps.

**Comment by powo01** [comment]
Thanks a lot for the useful response

the " DISTRO=LiserTV" does the successful build ... now I m able the create a working image and also a rebase to the lastest commits of the libreelec 9.2 branch is working successfull

thanks again for the response and your work in general
